### ISSUE TITLE
一些看法

### ISSUE THREAD

**Issue by ylyxf** [Erin123456/Erin#3]
1、且做且保存，是一个很好的使用电脑的习惯。我觉得光像你说的那样，还不够，如果电脑崩溃了，硬盘坏了，怎么办？考虑一下，使用这个github的工具，把你的照片备份上来，好好组织组织，可以开个画展呢~
2、QQ有改热键的功能：
![qq](https://cloud.githubusercontent.com/assets/3871920/10747089/50f5a376-7c8c-11e5-8412-67a4aee00c17.jpg)

**Comment by Erin123456** [comment]
Thank you very much,teacher Yu.
